default:
  outputs:
    dev:
      account: "{{ env_var('DBT_SNOWFLAKE_DEV_ACCOUNT') }}"
      database: "{{ env_var('DBT_SNOWFLAKE_DEV_DATABASE') }}"
      password: "{{ env_var('DBT_SNOWFLAKE_DEV_CI_PASSWORD') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_DEV_CI_ROLE') }}"
      schema: "{{ env_var('DBT_SNOWFLAKE_DEV_CI_SCHEMA') }}"
      threads: 4
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_DEV_CI_USER') }}"
      warehouse: "{{ env_var('DBT_SNOWFLAKE_DEV_CI_WAREHOUSE') }}"
  target: dev
